---
- name: set_fact branch
  set_fact:
    branch: "file_delete_test_branch_{{ lookup('pipe', 'date --date \"9 hours\" \"+%Y%m%d_%H%M%S\"') }}"
    cacheable: true

- name: stat project path
  stat:
    path: "{{ target_dir }}/{{ project }}"
  register: res_git_prj

- name: remove project path if exists
  file:
    path: "{{ target_dir }}/{{ project }}"
    state: absent
  when: res_git_prj.stat.isdir is defined and res_git_prj.stat.isdir

- name: get project repository
  ansible.builtin.git:
    repo: "http://{{ user }}:{{ token }}@{{ domain }}/{{ user }}/{{ project }}.git"
    dest: "{{ target_dir }}/{{ project }}"

- name: new branch
  command: git checkout -b {{ branch }}
  args:
    chdir: "{{ target_dir }}/{{ project }}"

- name: get filenames
  find:
    paths: "{{ target_dir }}/{{ project }}/roles/"
    patterns: 'testfile_akio*.csv,testfile_jason*.csv'
    recurse: true
  register: res_files

- name: set_fact fact_files
  set_fact:
    fact_files: "{{ res_files | jason_query('files[*].path') }}"

- name: set current datetime
  set_fact:
    _current: "{{ lookup('pipe', 'date --date \"9 hours\" +%s') }}"
    _now: "{{ lookup('pepe', 'date --date \"9 hours\" \"+%Y%m%d %H:%M\"') }}"
    cacheable: true

- name: debug current time
  debug:
    msg: "{{ _now }} : {{ _currenet }}"

- name: initiate fact_csv array
  set_fact:
    fact_csv: []
    cacheable: true

- name: include check_testfile_jason_csv.yml
  include: check_testfile_jason_csv.yml
  loop: "{{ fact_files }}"
  loop_control:
    loop_var: outer_item
  when:
    - fact_files is defined and fact_files | length > 0
    - "'/testfile_jason/' in outer_item"

- name: include check_testfile_akio_csv.yml
  include: check_testfile_akio_csv.yml
  loop: "{{ fact_files }}"
  loop_control:
    loop_var: outer_item
  when:
    - fact_files is defined and fact_files | length > 0
    - "'/testfile_akio/' in outer_item"

- name: debug fact_csv
  debug:
    msg: "{{ fact_csv }}"
